#!/bin/sh

set -ex

trap bash EXIT

createdb dumptest
psql -1 -v ON_ERROR_STOP=1 dumptest <<SQL
create extension supa_audit cascade;
create table test(id int generated by default as identity primary key, name text);
select audit.enable_tracking('public.test'::regclass);
insert into test(name)values('hi');
insert into test(name)values('ho');
SQL

test "$(psql dumptest --no-psqlrc -Atc "select count(*) from audit.record_version")" -eq 2

pg_dump dumptest > dumptest.sql

createdb restoretest

psql -1 -v ON_ERROR_STOP=1 restoretest < dumptest.sql

test "$(psql restoretest --no-psqlrc -Atc "select count(*) from audit.record_version")" -eq 2
